import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('http://10.8.90.17:8888/#/home/bond');
    await page.getByRole('button', { name: 'Đăng nhập' }).click();
    await page.getByRole('textbox', { name: 'Tên đăng nhập' }).click();
    await page.getByRole('textbox', { name: 'Tên đăng nhập' }).fill('010C0003433');
    await page.getByRole('textbox', { name: 'Mật khẩu' }).click();
    await page.getByRole('textbox', { name: 'Mật khẩu' }).fill('123456');
    await page.getByRole('button', { name: 'Đăng nhập' }).click();
    await page.getByRole('textbox', { name: 'Tên đăng nhập' }).click();
    await page.getByRole('textbox', { name: 'Tên đăng nhập' }).press('ArrowLeft');
    await page.getByRole('textbox', { name: 'Tên đăng nhập' }).press('ArrowLeft');
    await page.getByRole('textbox', { name: 'Tên đăng nhập' }).press('ArrowLeft');
    await page.getByRole('textbox', { name: 'Tên đăng nhập' }).press('ArrowLeft');
    await page.getByRole('textbox', { name: 'Tên đăng nhập' }).fill('010C003433');
    await page.getByRole('button', { name: 'Đăng nhập' }).click();
    await page.getByText('N00001661 - Thường').click();
    await page.getByText('D00000121 - Phái sinh', { exact: true }).click();
    await page.getByText('Đặt lệnh').click();
    await page.locator('input[name="inputEl1"]').fill('1');
    await page.locator('input[name="inputEl2"]').fill('1');
    await page.locator('input[name="inputEl3"]').fill('1');
    await page.getByRole('button', { name: 'Xác nhận' }).click();
    await page.getByText('1,440.1').dblclick();
    await page.getByRole('textbox', { name: 'Số lượng' }).click();
    await page.getByRole('textbox', { name: 'Số lượng' }).fill('1');
    await page.getByRole('button', { name: 'Bán' }).click();
    await page.getByRole('button', { name: 'Đặt lệnh' }).click();
    await page.getByText('Đặt lệnh').click();
    await page.getByText('Vị thế').click();
    await page.getByRole('row', { name: 'VN30F2509 Mua 1 0 2 1,700.10' }).locator('span').nth(4).click();
    await page.getByRole('row', { name: '41I2F9000 Mua 1 0 1 14,001.00' }).locator('span').nth(4).click();
    await page.getByRole('button', { name: 'Xác nhận' }).click();
    await page.getByRole('row', { name: '41I2F9000 Mua 1 0 2 14,001.00' }).locator('span').nth(2).click();
    await page.getByText('Sổ lệnh (3)').click();
    await page.getByText('Lịch sử lệnh').click();
    await page.getByText('Sổ lệnh điều kiện').click();
    await page.getByText('Vị thế đóng').click();
    await page.getByText('Báo cáo Lãi/Lỗ').click();
    await page.getByLabel('onRequestClose Example').getByText('Tài sản').click();
});